language: java
jdk:
  - oraclejdk8
install:
  - mvn test jacoco:report coveralls:report -B -V
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      all_branches: true
      repo: corbel-platform/corbel
      jdk: oraclejdk8
after_success:
  - docker login-u $DOCKER_USER -p $DOCKER_PASS
  - mvn install -Dmaven.test.skip=true -DdockerBuild=true -DpushImage -Ddocker.organization=devialab -Ddocker.name.prefix=corbel-